use_frameworks!

platform :ios, '8.0'

target 'LcyNetWork_Example' do
  pod 'LcyNetWork', :path => '../'

  target 'LcyNetWork_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
